#!/bin/sh
# Generate the `resolver` line the Gemini proxy needs.
#
# proxy_pass with variables in it makes nginx resolve the upstream at request
# time, which requires an explicit resolver. Declaring the upstream in an
# `upstream {}` block instead would resolve it once at startup — but then a DNS
# hiccup takes the *whole site* down with a config-load failure. Resolving per
# request fails safe: only the AI proxy 502s, the dashboard keeps serving.
set -eu

CONF=/etc/nginx/conf.d/00-resolver.conf

# Reuse the container's own nameservers; skip IPv6 entries, which nginx wants
# in [brackets] and which are usually unroutable here anyway.
nameservers=$(awk '/^[[:space:]]*nameserver/ && $2 !~ /:/ { printf "%s ", $2 }' /etc/resolv.conf 2>/dev/null || true)

if [ -z "$nameservers" ]; then
    echo "05-resolver.sh: no usable nameserver in /etc/resolv.conf, using public fallback"
    nameservers="1.1.1.1 8.8.8.8"
fi

# Normalise to exactly one trailing space before appending the options. Relying
# on awk's `printf "%s "` to leave one is a trap: the hardcoded fallback above
# has no trailing space, so the directive rendered as `8.8.8.8valid=30s` and
# nginx refused to start — precisely in the case the fallback exists to rescue.
nameservers=$(echo "$nameservers" | tr -s ' ' | sed 's/[[:space:]]*$//')

{
    echo "# generated by 05-resolver.sh at container start"
    echo "resolver ${nameservers} valid=30s ipv6=off;"
    echo "resolver_timeout 5s;"
} > "$CONF"

echo "05-resolver.sh: resolver ${nameservers}"
